### ISSUE TITLE
Colab button for '3. Interpreting LiteRate Results.' tutorial goes to '2_introduction_to_literate_final.ipynb'

### ISSUE THREAD

**Issue by benmarwick** [dsilvestro/lite-rate#1]
Thanks so much for the incredible documentation accompanying this software, so easy to read and follow. Everything about this work is amazing and so inspiring. 

I was reading through the tutorials and I'm not sure if the [Colab button](https://colab.research.google.com/drive/16fiaQkQo6Ng7N4YZsBoj3VVEA8HPfPKh) for "3. Interpreting LiteRate Results." links to the right notebook. It takes me to an IPython notebook named '2_introduction_to_literate_final.ipynb', which seems not quite right.

**Comment by kochbj** [comment]
Fixed it. Thanks Ben! Let me know if you have any other questions.
